steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install node_modules based on package.json'
    args: ['install']
  # NOTE: npx is used as workaround to allow serverless command to be found
  # https://github.com/serverless/serverless/issues/4889
  # - name: 'gcr.io/cloud-builders/npm'
  #   id: 'Install npx'
  #   args: ['install', '-g', 'npx']
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Serverless framework using npm'
    args: ['install', '-g', 'serverless']
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=keyfile.json.enc
      - --plaintext-file=keyfile.json
      - --location=us-central1
      - --keyring=${_KEYRING}
      - --key=${_KEY}
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Deploy serverless framework'
    entrypoint: bash
    args: 
      - '-c'
      - | 
          cd ./services
          npm install
          npx serverless deploy -v
substitutions:
  _KEYRING: projects/clear-veld-306519/locations/us-central1/keyRings/test_keyring
  _KEY: projects/clear-veld-306519/locations/us-central1/keyRings/test_keyring/cryptoKeys/my_test_key #copy resource name in console

#workspace/services 
#enable deployment manager api
#give kms decrypt role to gcloud service account (not created one)
#create service account for cloud build 
#generate keyfile from service account
#create keyring and key in GCP console, copy resource paths for step below
#encrypt in gcp cli
#gcloud kms encrypt --location "us-central1" --keyring "projects/clear-veld-306519/locations/us-central1/keyRings/test_keyring" --key "projects/clear-veld-306519/locations/us-central1/keyRings/test_keyring/cryptoKeys/my_test_key" --plaintext-file ./keyfile.json --ciphertext-file ./keyfile.json.enc
#place keyfile.json.enc into your github repo