steps:
  #npm install
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install node_modules based on package.json'
    args: ['install']
  # NOTE: npx is used as workaround to allow serverless command to be found
  # https://github.com/serverless/serverless/issues/4889
  # - name: 'gcr.io/cloud-builders/npm'
  #   id: 'Install npx'
  #   args: ['install', '-g', 'npx']
 #serverless install
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Serverless framework using npm'
    args: ['install', '-g', 'serverless']
  #decrypt keyfile.json.enc
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=keyfile.json.enc
      - --plaintext-file=keyfile.json
      - --location=us-central1
      - --keyring=${_KEYRING}
      - --key=${_KEY}
  #run unit test
  
  #serverless deploy
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Deploy serverless framework'
    entrypoint: bash
    args: 
      - '-c'
      - | 
          cd ./services
          npm install
          npx serverless deploy --verbose --env stg 
substitutions:
  _KEYRING: projects/clear-veld-306519/locations/us-central1/keyRings/test_keyring
  _KEY: projects/clear-veld-306519/locations/us-central1/keyRings/test_keyring/cryptoKeys/my_test_key #copy resource name in console GCP KMS
 
