steps:
  #npm install
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install node_modules based on package.json'
    args: ['install']
  # NOTE: npx is used as workaround to allow serverless command to be found
  # https://github.com/serverless/serverless/issues/4889
  # - name: 'gcr.io/cloud-builders/npm'
  #   id: 'Install npx'
  #   args: ['install', '-g', 'npx']
 #serverless install
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Serverless framework using npm'
    args: ['install', '-g', 'serverless']
  #run unit test
  # - name: 'gcr.io/cloud-builders/npm'
  #   id: 'Run unit tests'
  #   entrypoint: bash
  #   args:
  #     - '-c'
  #     - |
  #         chmod +x services/run-unit-tests.sh
  #         services/run-unit-tests.sh
  #decrypt keyfile.json.enc
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=keyfile.json.enc
      - --plaintext-file=keyfile.json
      - --location=us-west2
      - --keyring=${_KEYRING}
      - --key=${_KEY}
  #serverless deploy
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Deploy serverless framework'
    entrypoint: bash
    args: 
      - '-c'
      - | 
          chmod +x services/run-unit-tests.sh
          services/serverless_deploy_stg.sh
substitutions:
  _KEYRING: projects/iq-cloud-qa-functionality/locations/us-west2/keyRings/gcp-test
  _KEY: projects/iq-cloud-qa-functionality/locations/us-west2/keyRings/gcp-test/cryptoKeys/serverless-test #copy resource name in console GCP KMS
 
